import React from 'react';
import './AIApproach.css';  
import aiImage from './ai-integration.jpg'; // './' means same folder as AIApproach.js



const AiAssessmentScale = () => {
  return (
    <div className="ai-assessment-container">
      <h1 className="ai-assessment-title"><strong>OUR APPROACH TO THE USE OF AI IN EDUCATION</strong></h1>
      <section className="ai-section">
        <h2><strong>Introduction</strong></h2>
        <p>
        The introduction of artificial intelligence (AI) in education has transformed the way learning is undertaken and even presented new techniques of cheating. For example, the use of paraphrasing tools, essay-writing software, and automated solution generators presents a complication, as it becomes impossible to know who authored the work, whether a student or AI. Another notable instance is Generative AI (GenAI) tools like ChatGPT can take in a few words from a user and provide dilute explanations or offer rare essays at high quality. Thus, this tends to raise an issue on the effort that has been applied by the students on their pieces of submission. For this reason, various such institutions have been affected in relation to how they have adopted and did use the AI tools in education. 
        
        To address these challenges, we have incorporated the <a href="https://arxiv.org/pdf/2312.07086" target="_blank" className="ai-link"> AI Assessment Scale (AIAS)</a> into our knowledge base. The AIAS is designed to help educators and students reach a consensus on the appropriate use of GenAI tools in assessments. This scale represents a pioneering effort to promote a balanced integration of AI in education, acknowledging both the opportunities it presents and the challenges it creates.</p> 
      </section>

      {/* Explanation of the AI Assessment Scale */}
      <section className="ai-section">
        <h2><strong>Explanation of the AI Assessment Scale</strong></h2>
        
        <div className="ai-level">
          <h3>Level 1: No AI</h3>
          <div className="ai-level-content">
            <p>At this level, students are strictly not allowed to use Generative AI (GenAI). This is suited for assessment tasks that require students to depend solely on their own skills, knowledge, or understanding, or when the use of GenAI is impractical or not possible. While this level may involve examinations without technology, exam conditions are not always necessary. Examples include in-class activities such as technology-free discussions, debates, or oral assessments, as well as idea generation and group work that does not involve any technological aid. Viva-voce exams, Q&A sessions, or feedback discussions between students and educators can also be conducted without using GenAI.</p>
          </div>
        </div>

        <div className="ai-level">
          <h3>Level 2: AI-Assisted Idea Generation and Structuring</h3>
          <div className="ai-level-content">
            <p>At Level 2, students will have the opportunity to use GenAI to brainstorm, get feedback, and organize their ideas. There is however a requirement that no AI-generated content can be included in the final submission. When it comes to research and idea development, AI can be helpful, but the final product should still be human. It is possible for students to use AI in order to collaborate on brainstorming, where AI can generate ideas that can be refined by the students themselves, or they can use AI in order to formulate structured outline document. The use of artificial intelligence at this level allows students to get a deeper understanding of subjects while maintaining the integrity of the final work.  </p>
          </div>
        </div>

        <div className="ai-level">
          <h3>Level 3: AI-Assisted Editing</h3>
          <div className="ai-level-content">
            <p>This level is where AI assisted editing is allowed and students are permitted to refine and enhance their own work. Particularly in grammar, punctuation, word choice, and structural editing. In this stage, students who lack fluency in English and lack proficiency in writing can benefit. It can also aid in editing visual content, like image or video editing, but it cannot generate content from scratch. Students are expected to submit both their original and AI-assisted work for side-by-side comparisons. It can serve as a transitional stage until tasks can be fully adapted to include GenAI tools in the future.</p>
          </div>
        </div>

        <div className="ai-level">
          <h3>Level 4: AI Task Completion with Human Evaluation</h3>
          <div className="ai-level-content">
            <p>At this Level 4, learners are expected to incorporate the use of GenAI for selected parts of the assignments, with their attention primarily on analyzing and interpreting the output generated by AI. It must be ensured that students expose themselves to the critical evaluation of the outputs by the AI systems, focusing on their relevance, adequacy and quality. This stage reiterates the need for competence that encompasses understanding what AI solutions are about and where they can’t do. The flexibility of this level empowers students to incorporate AI at various stages of their process, promoting critical reflection and ensuring proper citation of AI contributions.</p>
          </div>
        </div>

        <div className="ai-level">
          <h3>Level 5: Full AI</h3>
          <div className="ai-level-content">
            <p>Level 5 gives students almost complete autonomy with AI. The use of AI for learning is possible, and GenAI tools might even be endorsed or recommended. In addition, AI will be used for working, thinking, like it's used in journalism, marketing, etc. Students can also use it to interact, correct, and improve content generation by AI in creating finished products or artifacts. Students at Level 5 are allowed to explore the consequences of AI in their projects, recognizing that AI is more than just creation.</p>
          </div>
        </div>
      </section>
      
      {/* Image Section */}
      <section className="ai-section">
        <img 
          src={aiImage}  // Use the imported image
          alt="AI Integration in Education" 
          className="ai-assessment-image" 
        />
      </section>
    </div>
  );
};

export default AiAssessmentScale;
